query windows registry for all COM ports
serialport/serialport-rs pull request #84
Opened 2023-03-17 23:20 UTC by Crzyrndm

As noted in #81 the list of COM ports in windows is incomplete when using v4.2.0

The easiest way to get the full list is to query the registry, although that gives basically zero information about the additional keys and as such this PR adds the ports with type "Unknown". This at least makes those ports visible through "available ports"

To my understanding, the device driver chooses which category it comes under causing the generic "ports" categroy to be incomplete

2023-03-25 03:19 UTC, Crzyrndm commented
See update. With this branch all COM ports are now found with full information
![image](https://user-images.githubusercontent.com/8765278/227689208-41a2619b-453d-41f9-a287-b57ac3c9689d.png)

2023-03-25 21:21 UTC, mlsvrts requested changes

2023-03-25 21:21 UTC, mlsvrts commented on src/windows/enumerate.rs
> +                SetupDiClassGuidsFromNameA(
We should probably be using the unicode (`SetupDiClassGuidsFromNameW`) or automatic (`SetupDiClassGuidsFromName`) versions of all windows functions. Otherwise devices from non-english speaking manufacturers or users in different localities may run into issues getting correct device names and information.

See: https://learn.microsoft.com/en-us/windows/win32/intl/unicode-in-the-windows-api

2023-03-26 08:46 UTC, Crzyrndm commented on src/windows/enumerate.rs
> +                SetupDiClassGuidsFromNameA(
Note that the API used hasn't changed in this PR, only the additional class being queried
https://github.com/serialport/serialport-rs/pull/84/files#diff-130c30419f44f04eb2238fe2f4482481ecc923ed216b379b214de25165b43dfeL37

I'm fine with updating to using the `_W` version (and update the registry query to do the same) here, or making a separate PR (which would make more sense to me if there's more instances than these two to update)

2023-03-26 23:32 UTC, mlsvrts commented on src/windows/enumerate.rs
> +                SetupDiClassGuidsFromNameA(
In that case, I think updating these in another PR instead of putting additional changes here makes more sense to me!

2023-03-26 23:34 UTC, mlsvrts approved these changes
I've tested this on my Windows 11 hardware and detection is still working well, thanks for the PR!

2023-03-27 11:14 UTC, Crzyrndm commented on src/windows/enumerate.rs
> +                SetupDiClassGuidsFromNameA(
See #89

2024-05-12 13:57 UTC, sirhcel commented
Thank you very much for your contribution @Crzyrndm and the review @mlsvrts! I finally got the time to look into it and check it out on the current _main_ branch.


> Filtering of devices returned by iterating has been inverted (`!name.starts_with("COM")` instead of the previous `name.starts_with("LPT")`) because there is potentially more than LPT devices to filter out
> 
> COM ports that don't belong to either of these categories will still be added to the "unknown" list ensuring that the list of available ports is always complete, even if missing detailed information

I changed the filtering back to just exclude ports starting with `LPT` for two reasons: First, there hasn't been any report on getting the wrong ports reported on Windows so far. Second, just selecting ports starting with `COM` would exclude virtual serial ports like the virtual null-modem ports I learned from in #187.

2024-05-12 14:00 UTC, merged